# Generated by Django 4.1.5 on 2023-01-16 20:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Fuel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gas', models.FloatField(verbose_name='gas(euro/MWh)')),
                ('kerosine', models.FloatField(verbose_name='kerosine(euro/MWh)')),
                ('co2', models.IntegerField(verbose_name='co2(euro/ton)')),
                ('wind_percentage', models.IntegerField(verbose_name='wind(%)')),
            ],
        ),
        migrations.CreateModel(
            name='Plant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('p', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Powerplant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('type', models.CharField(max_length=100)),
                ('efficiency', models.FloatField()),
                ('pmin', models.IntegerField()),
                ('pmax', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Payload',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('load', models.IntegerField()),
                ('fuels', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='loader.fuel')),
                ('powerplants', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='loader.powerplant')),
            ],
        ),
    ]
